# Generated by Django 4.2.4 on 2023-08-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='fup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=500)),
            ],
        ),
    ]
